version:  "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./:/app
    environment:
      - PORT=3000
    
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ads
      - MONGO_INITDB_ROOT_PASSWORD=ads
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo-db:
    # env_file:
    #   - ./.env 