version:  "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build: .
    image: aruna1994/node-app
    depends_on:
      - mongo
    volumes:
      - ./:/app
    environment:
      - PORT=3000
      
    
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ads
      - MONGO_INITDB_ROOT_PASSWORD=ads
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo-db:
    # env_file:
    #   - ./.env 